[package]
name = "osmnodecache"
version = "0.7.0"
authors = ["Yuri Astrakhan <YuriAstrakhan@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Flat file OSM node cache to store (latitude,longitude) pairs as indexed entries"
repository = "https://github.com/nyurik/osm-node-cache"
readme = "README.md"
keywords = ["osm", "cache"]
categories = ["caching"]
build = "build.rs"

[dependencies]
anyhow = "1.0.53"
bincode = "1.3.3"
dashmap = { version = "5.1.0", features = ["serde"] }
memmap2 = "0.5.3"
serde = "1.0.136"
serde_json = "1.0.78"

[dev-dependencies]
rand = "0.8.4"
rayon = "1.5.1"

[build-dependencies]
rustc_version = "0.4.0"

[features]
nightly = []
# If enabled, will not delete intermediate files generated during unit tests
keeptestfiles = []
