[package]
name = "osmnodecache"
version = "0.1.0"
authors = ["Yuri Astrakhan <YuriAstrakhan@gmail.com>"]
edition = "2021"

[dependencies]
memmap2 = "0.5.0"
anyhow = "1.0.47"
bytesize = { version = "1.1.0", features = ["serde"] }

[dev-dependencies]
rayon = "1.5.1"
rand = "0.8.4"
