[package]
name = "osmnodecache"
version = "0.8.0"
authors = ["Yuri Astrakhan <YuriAstrakhan@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Flat file OSM node cache to store (latitude,longitude) pairs as indexed entries"
repository = "https://github.com/nyurik/osm-node-cache"
keywords = ["osm", "cache"]
categories = ["caching"]
build = "build.rs"

[dependencies]
bincode = "1"
dashmap = { version = "5", features = ["serde"] }
memmap2 = "0.5"
serde = "1"
serde_json = "1"
thiserror = "1"

[dev-dependencies]
rand = "0.8"
rayon = "1"

[build-dependencies]
rustc_version = "0.4"

[features]
nightly = []
# If enabled, will not delete intermediate files generated during unit tests
keeptestfiles = []
