[package]
name = "osmnodecache"
version = "0.6.0"
authors = ["Yuri Astrakhan <YuriAstrakhan@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Flat file OSM node cache to store (latitude,longitude) pairs as indexed entries"
repository = "https://github.com/nyurik/osm-node-cache"
readme = "README.md"
keywords = ["osm", "cache"]
categories = ["caching"]
build = "build.rs"

[dependencies]
memmap2 = "0.5.0"
anyhow = "1.0.51"
dashmap = { version = "5.0.0", features = ["serde"] }
serde = "1.0.131"
serde_json = "1.0.73"
bincode = "1.3.3"

[dev-dependencies]
rayon = "1.5.*"
rand = "0.8.*"

[build-dependencies]
rustc_version = "0.4.*"

[features]
nightly = []
# If enabled, will not delete intermediate files generated during unit tests
keeptestfiles = []
