[package]
name = "osmnodecache"
version = "0.3.0"
authors = ["Yuri Astrakhan <YuriAstrakhan@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Flat file OSM node cache to store (latitude,longitude) pairs as indexed entries"
repository = "https://github.com/nyurik/osm-node-cache"
readme = "README.md"
keywords = ["osm", "cache"]
categories = ["caching"]
build = "build.rs"

[dependencies]
memmap2 = "0.5.0"
anyhow = "1.0.51"

[dev-dependencies]
rayon = "1.5.*"
rand = "0.8.*"

[build-dependencies]
rustc_version = "0.4.*"

[features]
nightly = []
