[package]
name = "osmnodecache"
version = "0.1.0"
authors = ["Yuri Astrakhan <YuriAstrakhan@gmail.com>"]
edition = "2018"

[dependencies]
#osmpbf = "0.2.5"
memmap2 = "0.5.0"
#byteorder = "1.4.3"
anyhow = "1.0.47"
bytesize = { version = "1.1.0", features = ["serde"] }
#rayon = "1.5.1"
