[package]
name = "bench"
description = "Benchmarks to run with `cargo bench`"
version = "0.0.0"
edition = "2021"
publish = false

[[bench]]
name = "bench"
harness = false

[dependencies]
osmnodecache = { path = ".." }

[dev-dependencies]
criterion = "0.7"
